name: flaskpy
channels:
  - defaults
dependencies:
  - certifi=2018.10.15=py37_0
  - pip=18.1=py37_0
  - python=3.7.1=h33f27b4_4
  - setuptools=40.5.0=py37_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.15.26706=h3a45250_0
  - wheel=0.32.2=py37_0
  - wincertstore=0.2=py37_0
  - pip:
    - click==7.0
    - flask==1.0.2
    - itsdangerous==1.1.0
    - jinja2==2.10
    - markupsafe==1.1.0
    - werkzeug==0.14.1
prefix: D:\tools\Anaconda3\envs\flaskpy

